image: peepe/cmake-ssh-lcov

stages:
  - build
  - test
  - analyze

cache:
  paths:
    - runtime/*

build:
  stage: build
  script:
    - ssh-agent sh -c 'ssh-add ~/.ssh/id_rsa; git submodule init'
    - ssh-agent sh -c 'ssh-add ~/.ssh/id_rsa; git submodule update'
    - mkdir -p runtime
    - cd runtime
    - cmake ..
    - make
  artifacts:
    paths:
      - runtime/


unit-test:
  stage: test
  script:
    - cd runtime 
    - ctest --verbose
  artifacts:
    reports:
      junit: *test_result.xml



cpplint:
  stage: analyze
  script:
    - cd runtime
    - make cpplint

code-coverage:
  stage: analyze
  script:
    - cd runtime
    - make coverage
  artifacts:
    paths:
      - runtime/lcov-html
