variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - analyze

build:
  stage: build
  script:
    - mkdir runtime
    - cd runtime
    - cmake ..
    - make
  artifacts:
    paths:
      - runtime/

unit-test:
  stage: test
  script:
    - cd runtime 
    - ctest --verbose

cpplint:
  stage: analyze
  script:
    - cd runtime
    - make cpplint

code-coverage:
  stage: analyze
  script:
    - cd runtime
    - make coverage
