language: cpp

env:
  global: 
    - LINUX_DIST=bionic
    - CXX_FLAGSS="-Wall -pedantic"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gnuplot
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p runtime
  - cd runtime 
  - cmake -DCMAKE_CXX_FLAGS=${CXX_FLAGSS} -DCMAKE_BUILD_TYPE=release -DBUILD_TESTS=ON ..
  - make -j2
  - ctest --output-on-failure
