language: cpp

env:
  global: 
    - LINUX_DIST=bionic
    - CXX_FLAGSS="-Wall -pedantic"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script:
  - mkdir -p runtime
  - cd runtime 
  - cmake -DCMAKE_CXX_FLAGS=${CXX_FLAGSS} -DCMAKE_BUILD_TYPE=release -DBUILD_TESTS=ON ..
  - make 
  - ctest
